name: Build

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]"

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: Step 1 - install dependencies
        run: npm install
      - name: Step 2 - build the frontend
        run: npm run build
      - name: Step 3 - run transloco optimize
        run: npm run transloco:optimize
      - name: Step 4 - package with Electron builder and clean release folder
        run: npm run release:linux
      - name: Step 5 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: servihelper-linux
          path: release

  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: Step 1 - install dependencies
        run: npm install
      - name: Step 2 - build the frontend
        run: npm run build
      - name: Step 3 - run transloco optimize
        run: npm run transloco:optimize
      - name: Step 4 - package with Electron builder and clean release folder
        run: npm run release:mac:universal
      - name: Step 5 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: servihelper-mac
          path: release

  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - name: Step 1 - install dependencies
        run: npm install
      - name: Step 2 - build the frontend
        run: npm run build
      - name: Step 3 - run transloco optimize
        run: npm run transloco:optimize
      - name: Step 4 - package with Electron builder and clean release folder
        run: npm run release:windows
      - name: Step 5 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: servihelper-windows
          path: release
